package phonebook;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
//import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.GrayColor;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
//import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javafx.collections.ObservableList;

/**Pdf creator class.
 * Instantiate it if you want to create a printable version of a list
 * @author Zed
 */
public class PdfGeneration {
    /** This method creates a pdf document containing the entries of the ContactBook.
     @param fileName the name of the file
     @param data the list containing the entries.
     */
    public void pdfGeneration(String fileName, ObservableList<Person> data) {
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(fileName + ".pdf"));
            document.open();
            
            //Company logo
            Image image1 = Image.getInstance(getClass().getResource("/logo2.jpg"));
            image1.scaleToFit(400, 172);
            image1.setAbsolutePosition(170f, 650f);
            document.add(image1);
            //document.add(new Paragraph("\n\n\n\n\n\n\n\n" + text, FontFactory.getFont("betutipus", BaseFont.IDENTITY_H, BaseFont.EMBEDDED)));
            document.add(new Paragraph("\n\n\n\n\n\n\n\n\n\n\n\n\n"));
            
            //Table
            float[] columnWidths = {2,4,4,6};
            PdfPTable table = new PdfPTable(columnWidths);
            table.setWidthPercentage(100);
            //main-header, the title of the table
            PdfPCell cell = new PdfPCell(new Phrase("Contact list"));
            cell.setBackgroundColor(GrayColor.GRAYWHITE);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setColspan(4); //width of the main header cell
            table.addCell(cell);
            //the 3 header cells
            table.getDefaultCell().setBackgroundColor(new GrayColor(0.75f));
            table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell("ID number");
            table.addCell("Surname");
            table.addCell("Given name");
            table.addCell("E-mail address");
            table.setHeaderRows(1);
            //content cells
            table.getDefaultCell().setBackgroundColor(GrayColor.GRAYWHITE);
            table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
            for(int i = 1; i <= data.size(); i++){
                Person actualPerson = data.get(i-1);
                table.addCell(""+i);
                table.addCell(actualPerson.getLastName());
                table.addCell(actualPerson.getFirstName());
                table.addCell(actualPerson.getEmail());
            }            
            document.add(table);
            
            //Signature
            Chunk signature = new Chunk("\n\n Generated by ContactBook application.");
            Paragraph base = new Paragraph(signature);
            document.add(base);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        document.close();
    }
    
}
